function(v)
				getgenv().fastdrink = v
				while getgenv().fastdrink do wait()
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Starter Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Second Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Third Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Fourth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Fifth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Sixth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Seventh Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Eighth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Ninth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Atomic Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Omega Burp Juice")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Thunder Fizz")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Garlic Juice")
				end
			end)

			autofarm:Toggle("Auto Drink", function(v)
				getgenv().autodrink = v
				while getgenv().autodrink do wait(2.4)
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Starter Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Second Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Third Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Fourth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Fifth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Sixth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Seventh Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Eighth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Ninth Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Atomic Drink")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Omega Burp Juice")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Thunder Fizz")
					game.ReplicatedStorage.RemoteEvents.DrinkEvent:FireServer("Garlic Juice")
				end
			end)
